"""adicionar tabela de horarios (aulas e monitorias)

Revision ID: 06e3f2a484ef
Revises: 27917be8e91a
Create Date: 2026-08-16 22:01:24.198648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06e3f2a484ef'
down_revision = '27917be8e91a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disciplina_turma_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.Column('dia_semana', sa.String(length=10), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fim', sa.Time(), nullable=False),
    sa.Column('local', sa.String(length=120), nullable=True),
    sa.CheckConstraint("(categoria = 'aula' AND tipo IS NOT NULL) OR (categoria = 'monitoria' AND tipo IS NULL)", name='ck_horario_tipo_conforme_categoria'),
    sa.CheckConstraint("categoria IN ('aula', 'monitoria')", name='ck_horario_categoria'),
    sa.CheckConstraint("dia_semana IN ('segunda', 'terca', 'quarta', 'quinta', 'sexta', 'sabado', 'domingo')", name='ck_horario_dia_semana'),
    sa.CheckConstraint('hora_fim > hora_inicio', name='ck_horario_fim_apos_inicio'),
    sa.ForeignKeyConstraint(['disciplina_turma_id'], ['disciplina_turma.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('horarios')
    # ### end Alembic commands ###
