"""adicionar professores, emails, telefones e regencias; disciplina_turma vira entidade com pk propria

Revision ID: 21fbb71e5634
Revises: 2770a574c167
Create Date: 2026-08-16 21:43:01.081344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21fbb71e5634'
down_revision = '2770a574c167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('apelido', sa.String(length=60), nullable=False),
    sa.Column('biografia', sa.Text(), nullable=True),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('professor_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('professor_id', 'email')
    )
    op.create_table('professor_telefones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('telefone', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('professor_id', 'telefone')
    )
    # disciplina_turma tinha PK composta (disciplina_id, turma_id); agora
    # precisa de um id proprio de surrogate key para ser referenciada por
    # regencias. A tabela esta vazia neste ambiente, entao recriamos.
    op.drop_table('disciplina_turma')
    op.create_table('disciplina_turma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disciplina_id', 'turma_id')
    )

    op.create_table('regencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disciplina_turma_id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('principal', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['disciplina_turma_id'], ['disciplina_turma.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disciplina_turma_id', 'professor_id')
    )
    with op.batch_alter_table('regencias', schema=None) as batch_op:
        batch_op.create_index('ix_regencia_um_principal_por_oferta', ['disciplina_turma_id'], unique=True, postgresql_where=sa.text('principal'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regencias', schema=None) as batch_op:
        batch_op.drop_index('ix_regencia_um_principal_por_oferta', postgresql_where=sa.text('principal'))

    op.drop_table('regencias')

    op.drop_table('disciplina_turma')
    op.create_table('disciplina_turma',
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('disciplina_id', 'turma_id')
    )

    op.drop_table('professor_telefones')
    op.drop_table('professor_emails')
    op.drop_table('professores')
    # ### end Alembic commands ###
