"""adicionar unique constraint ano+semestre+codigo em turmas

Revision ID: 2770a574c167
Revises: fd713546fea3
Create Date: 2026-08-16 21:33:38.046080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2770a574c167'
down_revision = 'fd713546fea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turmas', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['ano', 'semestre', 'codigo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turmas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
