"""adicionar tabela de avisos

Revision ID: 27917be8e91a
Revises: 4e482bb29bf0
Create Date: 2026-08-16 21:55:28.591000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27917be8e91a'
down_revision = '4e482bb29bf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=True),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('data_publicacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id', 'turma_id'], ['disciplina_turma.disciplina_id', 'disciplina_turma.turma_id'], ),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avisos')
    # ### end Alembic commands ###
