"""adicionar monitores e monitorias

Revision ID: 4e482bb29bf0
Revises: 21fbb71e5634
Create Date: 2026-08-16 21:48:58.176089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e482bb29bf0'
down_revision = '21fbb71e5634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('monitorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disciplina_turma_id', sa.Integer(), nullable=False),
    sa.Column('monitor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_turma_id'], ['disciplina_turma.id'], ),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disciplina_turma_id', 'monitor_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monitorias')
    op.drop_table('monitores')
    # ### end Alembic commands ###
