"""adicionar syllabus (pdf) em disciplinas

Revision ID: 7c13049a72f9
Revises: 91f71afcffd2
Create Date: 2026-08-16 22:11:17.312435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c13049a72f9'
down_revision = '91f71afcffd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disciplinas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caminho_syllabus', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('nome_arquivo_syllabus', sa.String(length=255), nullable=True))
        batch_op.create_check_constraint('ck_disciplina_syllabus_campos_coerentes', '(caminho_syllabus IS NULL AND nome_arquivo_syllabus IS NULL) OR (caminho_syllabus IS NOT NULL AND nome_arquivo_syllabus IS NOT NULL)')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disciplinas', schema=None) as batch_op:
        batch_op.drop_constraint('ck_disciplina_syllabus_campos_coerentes', type_='check')
        batch_op.drop_column('nome_arquivo_syllabus')
        batch_op.drop_column('caminho_syllabus')

    # ### end Alembic commands ###
