"""adicionar tabela de recursos e recurso_vinculos

Revision ID: 91f71afcffd2
Revises: 06e3f2a484ef
Create Date: 2026-08-16 22:07:16.124497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91f71afcffd2'
down_revision = '06e3f2a484ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('caminho_arquivo', sa.String(length=500), nullable=True),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.CheckConstraint("(tipo = 'arquivo' AND caminho_arquivo IS NOT NULL AND url IS NULL) OR (tipo = 'link' AND url IS NOT NULL AND caminho_arquivo IS NULL)", name='ck_recurso_campos_conforme_tipo'),
    sa.CheckConstraint("tipo IN ('arquivo', 'link')", name='ck_recurso_tipo'),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recurso_vinculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disciplina_id', 'turma_id'], ['disciplina_turma.disciplina_id', 'disciplina_turma.turma_id'], ),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['recurso_id'], ['recursos.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recurso_id', 'disciplina_id', 'turma_id')
    )
    with op.batch_alter_table('recurso_vinculos', schema=None) as batch_op:
        batch_op.create_index('ix_recurso_vinculo_disciplina_unico_sem_turma', ['recurso_id', 'disciplina_id'], unique=True, postgresql_where=sa.text('turma_id IS NULL'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurso_vinculos', schema=None) as batch_op:
        batch_op.drop_index('ix_recurso_vinculo_disciplina_unico_sem_turma', postgresql_where=sa.text('turma_id IS NULL'))

    op.drop_table('recurso_vinculos')
    op.drop_table('recursos')
    # ### end Alembic commands ###
