"""adicionar slug e geral em recursos

Revision ID: a48bbe5a1d2b
Revises: c612a55ce8de
Create Date: 2026-08-17 13:02:32.612107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a48bbe5a1d2b'
down_revision = 'c612a55ce8de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recursos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('geral', sa.Boolean(), server_default='false', nullable=False))
        batch_op.create_unique_constraint(None, ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recursos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('geral')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
