"""adicionar apelido, ativa e data_desativacao em disciplinas

Revision ID: ae0ae68b97b6
Revises: bc94abd4635e
Create Date: 2026-08-16 21:23:07.203707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae0ae68b97b6'
down_revision = 'bc94abd4635e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disciplinas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apelido', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('ativa', sa.Boolean(), server_default='true', nullable=False))
        batch_op.add_column(sa.Column('data_desativacao', sa.Date(), nullable=True))
        batch_op.create_check_constraint('ck_disciplina_ativa_data_desativacao', '(ativa AND data_desativacao IS NULL) OR (NOT ativa AND data_desativacao IS NOT NULL)')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disciplinas', schema=None) as batch_op:
        batch_op.drop_constraint('ck_disciplina_ativa_data_desativacao', type_='check')
        batch_op.drop_column('data_desativacao')
        batch_op.drop_column('ativa')
        batch_op.drop_column('apelido')

    # ### end Alembic commands ###
