"""adicionar semanas, aulas, atividades e atividade_historico

Revision ID: c612a55ce8de
Revises: 7c13049a72f9
Create Date: 2026-08-17 10:45:01.107682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c612a55ce8de'
down_revision = '7c13049a72f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semanas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disciplina_turma_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('objetivos', sa.Text(), nullable=True),
    sa.Column('antes_das_aulas', sa.Text(), nullable=True),
    sa.Column('depois_da_semana', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['disciplina_turma_id'], ['disciplina_turma.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disciplina_turma_id', 'numero'),
    sa.UniqueConstraint('id', 'disciplina_turma_id')
    )
    op.create_table('aulas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semana_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_turma_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('objetivos', sa.Text(), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('preparacao', sa.Text(), nullable=True),
    sa.Column('material', sa.Text(), nullable=True),
    sa.Column('exercicios', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['disciplina_turma_id'], ['disciplina_turma.id'], ),
    sa.ForeignKeyConstraint(['semana_id', 'disciplina_turma_id'], ['semanas.id', 'semanas.disciplina_turma_id'], ),
    sa.ForeignKeyConstraint(['semana_id'], ['semanas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disciplina_turma_id', 'numero')
    )
    op.create_table('atividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disciplina_turma_id', sa.Integer(), nullable=False),
    sa.Column('aula_id', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.String(length=20), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('data_publicacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('prazo', sa.DateTime(timezone=True), nullable=True),
    sa.Column('objetivos', sa.Text(), nullable=True),
    sa.Column('pre_requisitos', sa.Text(), nullable=True),
    sa.Column('especificacao', sa.Text(), nullable=True),
    sa.Column('arquivos_fornecidos', sa.Text(), nullable=True),
    sa.Column('como_executar', sa.Text(), nullable=True),
    sa.Column('como_testar', sa.Text(), nullable=True),
    sa.Column('o_que_entregar', sa.Text(), nullable=True),
    sa.Column('como_entregar', sa.Text(), nullable=True),
    sa.Column('criterios_avaliacao', sa.Text(), nullable=True),
    sa.Column('duvidas_frequentes', sa.Text(), nullable=True),
    sa.CheckConstraint("categoria IN ('exercicio', 'lista', 'pset', 'projeto', 'trabalho', 'lab')", name='ck_atividade_categoria'),
    sa.CheckConstraint('prazo IS NULL OR prazo > data_publicacao', name='ck_atividade_prazo_apos_publicacao'),
    sa.ForeignKeyConstraint(['aula_id'], ['aulas.id'], ),
    sa.ForeignKeyConstraint(['disciplina_turma_id'], ['disciplina_turma.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disciplina_turma_id', 'categoria', 'numero')
    )
    op.create_table('atividade_historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atividade_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['atividade_id'], ['atividades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atividade_historico')
    op.drop_table('atividades')
    op.drop_table('aulas')
    op.drop_table('semanas')
    # ### end Alembic commands ###
