"""turmas viram N:N com disciplinas, ganham slug/nome/apelido

Revision ID: fd713546fea3
Revises: ae0ae68b97b6
Create Date: 2026-08-16 21:32:35.911783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd713546fea3'
down_revision = 'ae0ae68b97b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disciplina_turma',
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('disciplina_id', 'turma_id')
    )
    with op.batch_alter_table('turmas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('nome', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('apelido', sa.String(length=60), nullable=False))
        batch_op.drop_constraint(batch_op.f('turmas_disciplina_id_ano_semestre_codigo_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['slug'])
        batch_op.drop_constraint(batch_op.f('turmas_disciplina_id_fkey'), type_='foreignkey')
        batch_op.drop_column('disciplina_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turmas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disciplina_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('turmas_disciplina_id_fkey'), 'disciplinas', ['disciplina_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('turmas_disciplina_id_ano_semestre_codigo_key'), ['disciplina_id', 'ano', 'semestre', 'codigo'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('apelido')
        batch_op.drop_column('nome')
        batch_op.drop_column('slug')

    op.drop_table('disciplina_turma')
    # ### end Alembic commands ###
